-- begin SATTR_BUSINESS_USER
alter table SATTR_BUSINESS_USER add constraint FK_SATTR_BUSINESS_USER_SYS_USER foreign key (SYS_USER_ID) references SEC_USER(ID)^
alter table SATTR_BUSINESS_USER add constraint FK_SATTR_BUSINESS_USER_COMPANY foreign key (COMPANY_ID) references SATTR_COMPANY(ID)^
create unique index IDX_SATTR_BUSINESS_USER_UNIQ_SYS_USER_ID on SATTR_BUSINESS_USER (SYS_USER_ID) ^
create index IDX_SATTR_BUSINESS_USER_SYS_USER on SATTR_BUSINESS_USER (SYS_USER_ID)^
create index IDX_SATTR_BUSINESS_USER_COMPANY on SATTR_BUSINESS_USER (COMPANY_ID)^
-- end SATTR_BUSINESS_USER
